name: simple_money_tracker
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  custom_utils:
    git: https://github.com/imsamgarg/custom_utils.git
  flutter:
    sdk: flutter

  sqflite_common_ffi: ^2.1.1+1
  flutter_riverpod: ^2.0.0-dev.9
  go_router: ^4.2.7
  sqflite: ^2.0.3
  intl: ^0.17.0
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.10.0
  mockito: ^5.3.0
  sqflite_common_ffi: ^2.1.1+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
